# Generated by Django 5.2.6 on 2025-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Is Partner Account'),
        ),
    ]
