# Generated by Django 5.2.6 on 2025-12-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
